// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD8hRHR_ej96KAVGI3VxCVWwM5vim--Jc',
    appId: '1:395769648162:web:f911c18df6fd9b5a24267b',
    messagingSenderId: '395769648162',
    projectId: 'simplekey',
    authDomain: 'simplekey.firebaseapp.com',
    storageBucket: 'simplekey.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdx_p0Gr4Sqtnc3FtmZb05wes_UO1xZEY',
    appId: '1:395769648162:android:259415a48b6b808524267b',
    messagingSenderId: '395769648162',
    projectId: 'simplekey',
    storageBucket: 'simplekey.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSg_mGlMs_gA5eci5JCGRRwztw9-3PsX0',
    appId: '1:395769648162:ios:7de48e506d2b05fc24267b',
    messagingSenderId: '395769648162',
    projectId: 'simplekey',
    storageBucket: 'simplekey.appspot.com',
    iosClientId: '395769648162-6crmid87suh7lpv7jljmf4q9nh6tbsus.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleKey',
  );
}
